name = "rck-is-takibi-api"
main = "worker.js"
compatibility_date = "2024-09-01"

[[r2_buckets]]
binding = "DATA_BUCKET"
bucket_name = "rck-is-takibi-data"

[vars]
WEB_PIN = "271179"
ADMIN_PIN = "0258"

# wrangler secret put UPLOAD_API_KEY
